// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDy-HXqf9qEJGIgiGGnh2Npa5SgFS5zYgY',
    appId: '1:758781699779:web:4b202d8db3b8a37a6be476',
    messagingSenderId: '758781699779',
    projectId: 'uilogin-c62bc',
    authDomain: 'uilogin-c62bc.firebaseapp.com',
    databaseURL: 'https://uilogin-c62bc-default-rtdb.firebaseio.com',
    storageBucket: 'uilogin-c62bc.appspot.com',
    measurementId: 'G-BP61ZPH8XH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq6PsjHD-824AVxf025REJAAc1CtqikUo',
    appId: '1:758781699779:android:74599d47c36ecc0c6be476',
    messagingSenderId: '758781699779',
    projectId: 'uilogin-c62bc',
    databaseURL: 'https://uilogin-c62bc-default-rtdb.firebaseio.com',
    storageBucket: 'uilogin-c62bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRyu2OkwUtTnf7jiNeacC6s13QP6GmYuA',
    appId: '1:758781699779:ios:dc3a5409050ef5816be476',
    messagingSenderId: '758781699779',
    projectId: 'uilogin-c62bc',
    databaseURL: 'https://uilogin-c62bc-default-rtdb.firebaseio.com',
    storageBucket: 'uilogin-c62bc.appspot.com',
    iosClientId: '758781699779-hk1cu9b7chf6t3bnh3roccukg0sng9in.apps.googleusercontent.com',
    iosBundleId: 'com.example.melonguard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRyu2OkwUtTnf7jiNeacC6s13QP6GmYuA',
    appId: '1:758781699779:ios:dc3a5409050ef5816be476',
    messagingSenderId: '758781699779',
    projectId: 'uilogin-c62bc',
    databaseURL: 'https://uilogin-c62bc-default-rtdb.firebaseio.com',
    storageBucket: 'uilogin-c62bc.appspot.com',
    iosClientId: '758781699779-hk1cu9b7chf6t3bnh3roccukg0sng9in.apps.googleusercontent.com',
    iosBundleId: 'com.example.melonguard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDy-HXqf9qEJGIgiGGnh2Npa5SgFS5zYgY',
    appId: '1:758781699779:web:767360153f9cf9246be476',
    messagingSenderId: '758781699779',
    projectId: 'uilogin-c62bc',
    authDomain: 'uilogin-c62bc.firebaseapp.com',
    databaseURL: 'https://uilogin-c62bc-default-rtdb.firebaseio.com',
    storageBucket: 'uilogin-c62bc.appspot.com',
    measurementId: 'G-EN0QCTH54V',
  );
}
